@baseUrl = http://localhost:7200/api/goods

# 创建商品
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "小米鱼缸",
  "price": 42.99,
  "pictureUrl": "https://img.pddpic.com/gaudit-image/2025-03-11/924d53c675061bdcc7722c0ce56bb7df.jpeg",
  "shopId":"6820a8626a5dcca93c98bc21"
}

### 获取所有商品
GET {{baseUrl}}?page=1&limit=3

### 获取所有商品 分页
POST {{baseUrl}}/list
Content-Type: application/json

{
  "page": 10,
  "limit":10
}

### 获取单个商品
GET {{baseUrl}}/6821f2f95abb5505df62252d

### 更新商品
PUT {{baseUrl}}/68205a6635afe21b74784ced
Content-Type: application/json

{
  "name": "更新后的商品名称",
  "description": "更新后的商品描述"
}

### 删除商品
DELETE {{baseUrl}}/6820566ef337a242a000017e

### 获取索引
GET {{baseUrl}}/getIndexes