@baseUrl = http://localhost:7200/api/order

###查看订单
GET {{baseUrl}}/684a862afd173eae470c4f1d

### 创建订单
POST {{baseUrl}}
Content-Type: application/json

{
  "goodsId":"684a862afd173eae470c4f1d",
  "number":2
}

### 订单列表
POST {{baseUrl}}/list
Content-Type: application/json

{
  "limit":3
}