@baseUrl = http://localhost:7200/api/skus

### 创建skus 对一个商品加商品属性 手动添加sku组

POST {{baseUrl}}
Content-Type: application/json

{
    "goods_id": "683e9aa41a9312e115ba11ec",
    "sku_groups_ids": [
        "6858fbb4c68e884f8f642a34",
        "6858fcdc3fa83d8b15d2375b"
    ]
}

### 查看skus

POST {{baseUrl}}/list
Content-Type: application/json

### 根据sku_id查看指定的sku详情
GET {{baseUrl}}/685a7bdeb63ebafa19d911ab