### 弃用 目前商品用sku_groups

@baseUrl = http://localhost:7200/api/skus

### 创建skus 对一个商品加商品属性 手动添加sku组

POST {{baseUrl}}
Content-Type: application/json

{
    "goods_id": "6836a7b77c25224250ab6d9b",
    "sku_groups_ids": [
        "6881a675a7bde0827bdf430a",
        "685a7bdeb63ebafa19d911a7",
        "685a7bdeb63ebafa19d911a5"
    ]
}

### 查看skus

POST {{baseUrl}}/list
Content-Type: application/json

### 根据sku_id查看指定的sku详情
GET {{baseUrl}}/685a7bdeb63ebafa19d911ab